<?php
namespace Database\Seeders;

use App\Models\Patient\Patient;
use Illuminate\Database\Seeder;

class PatientSeeder extends Seeder
{
    public function run()
    {
        $patients = [
            [
                'first_name' => 'John',
                'last_name' => 'Doe',
                'email' => 'john@example.com',
                'phone' => '123-555-0123',
                'patient_identifier' => 'PAT001',
                'birth_date' => '2015-01-01',
                'gender' => 1,
                'address' => '789 Patient St',
                'city' => 'Miami',
                'state' => 'FL',
                'zip' => '33101',
                'status' => 'active',
                'language' => 'English',
                'parent_guardian_name' => 'Jane Doe',
                'parent_gender' => 2,
                'parent_birth_date' => '1980-01-01',
                'parent_address' => '789 Patient St',
                'parent_city' => 'Miami',
                'parent_state' => 'FL',
                'parent_zip' => '33101',
                'relationship' => 'child',
                'location_id' => 1,
                'insurer_id' => 1,
                'insurance_identifier' => '123456789',
                'insurer_secondary_id' => 2,
                'insurance_secondary_identifier' => '987654321',
                'rbt_home_id' => 5,
                'bcba_home_id' => 3,
                'clin_director_id' => 1,
                'diagnosis_code' => 'F84.0',
                'education' => '2nd Grade',
                'school_name' => 'School of the Future',
                'school_number' => '123456',
                'pos_covered' => ["03", "12"],
                'welcome' => 'yes',
                'consent' => 'yes',
                'insurance_card' => 'yes',
                'mnl' => 'yes',
                'referral' => 'yes',
                'ados' => 'yes',
                'iep' => 'yes',
                'asd_diagnosis' => 'yes',
                'cde' => 'yes',
                'submitted' => 'yes',
                'eligibility' => 'yes',
                'interview' => 'receive',
                'referring_provider_first_name' => 'Jeremy',
                'referring_provider_last_name' => 'Smith',
                'referring_provider_npi' => '1234567890',
                'is_self_subscriber' => false,
                'emmployment' => false,
                'auto_accident' => false,
                'other_accident' => false,
                'deductible_individual_I_F' => '1000.00',
                'balance' => '500.00',
                'coinsurance' => '20',
                'copayments' => '30.00',
                'oop' => '2000.00',
                'elegibility_date' => '2024-01-01',
                'telehealth' => false,
                'pay' => false
            ],
            [
                'first_name' => 'Jane',
                'last_name' => 'Smith',
                'email' => 'jane@example.com',
                'phone' => '123-555-0124',
                'patient_identifier' => 'PAT002',
                'birth_date' => '2016-02-02',
                'gender' => 2,
                'address' => '987 Patient Ave',
                'city' => 'Orlando',
                'state' => 'FL',
                'zip' => '32801',
                'status' => 'active',
                'language' => 'Spanish',
                'parent_guardian_name' => 'John Smith',
                'parent_gender' => 1,
                'parent_birth_date' => '1980-01-01',
                'parent_address' => '789 Patient St',
                'parent_city' => 'Miami',
                'parent_state' => 'FL',
                'parent_zip' => '33101',
                'relationship' => 'child',
                'location_id' => 2,
                'insurer_id' => 2,
                'insurance_identifier' => '987654321',
                'insurer_secondary_id' => 3,
                'insurance_secondary_identifier' => '123456789',
                'rbt_home_id' => 6,
                'bcba_home_id' => 4,
                'clin_director_id' => 1,
                'diagnosis_code' => 'F84.0',
                'education' => '3rd Grade',
                'school_name' => 'School of the Future',
                'school_number' => '123456',
                'pos_covered' => ["03", "12"],
                'welcome' => 'yes',
                'consent' => 'yes',
                'insurance_card' => 'yes',
                'mnl' => 'yes',
                'referral' => 'yes',
                'ados' => 'yes',
                'iep' => 'yes',
                'asd_diagnosis' => 'yes',
                'cde' => 'yes',
                'submitted' => 'yes',
                'eligibility' => 'yes',
                'interview' => 'pending',
                'referring_provider_first_name' => 'Jeremy',
                'referring_provider_last_name' => 'Smith',
                'referring_provider_npi' => '1234567890',
                'is_self_subscriber' => false,
                'emmployment' => false,
                'auto_accident' => false,
                'other_accident' => false,
                'deductible_individual_I_F' => '2000.00',
                'balance' => '1000.00',
                'coinsurance' => '20',
                'copayments' => '40.00',
                'oop' => '3000.00',
                'elegibility_date' => '2024-01-01',
                'telehealth' => false,
                'pay' => false
            ]
        ];

        foreach ($patients as $patient) {
            Patient::create($patient);
        }
    }
}
