---
deployment:
  tasks:
    - export DEPLOYPATH=/home/z779cvj9zm4g/public_html/aba-dev.malcolmcordova.com/backend-api-aba/ # Reemplaza con tu ruta de despliegue
    - echo Starting>> $DEPLOYPATH/deploy.log 2>&1
    - /bin/cp -R * $DEPLOYPATH >> $DEPLOYPATH/deploy.log 2>&1
    - rm -rf $DEPLOYPATH/.git >> $DEPLOYPATH/deploy.log 2>&1 # Eliminar la carpeta .git
    - /bin/cp -R .cpanel.yml $DEPLOYPATH >> $DEPLOYPATH/deploy.log 2>&1
    - /bin/cp -R .env $DEPLOYPATH >> $DEPLOYPATH/deploy.log 2>&1
    - /bin/cp -R .htaccess $DEPLOYPATH >> $DEPLOYPATH/deploy.log 2>&1
    - cd $DEPLOYPATH >> $DEPLOYPATH/deploy.log 2>&1
    - php /opt/cpanel/composer/bin/composer update >> $DEPLOYPATH/deploy.log 2>&1
    # - php /opt/cpanel/composer/bin/composer install --optimize-autoloader
    # - php /opt/cpanel/composer/bin/composer install --no-dev --optimize-autoloader
    - php artisan l5-swagger:generate >> $DEPLOYPATH/deploy.log 2>&1
    # - php artisan migrate --force
    # - php artisan config:cache
    # - php artisan route:cache
    # - php artisan view:cache
    # - php artisan migrate:fresh --seed
    - php artisan migrate --path=/database/migrations/2024_11_07_225859_create_claims_table.php
    # - php artisan db:seed --class=TipoDemoraSeeder
